
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 63)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MOVE_RIGHT = 24;
  public static final int RBRACK = 18;
  public static final int TIMES = 5;
  public static final int PLUS = 3;
  public static final int RPAREN = 8;
  public static final int SEMI = 2;
  public static final int MOVE_UP = 22;
  public static final int LBRACK = 17;
  public static final int END = 16;
  public static final int SET_COLOR = 25;
  public static final int MOVE_LEFT = 23;
  public static final int LPAREN = 7;
  public static final int COLON = 10;
  public static final int ID = 27;
  public static final int DO = 15;
  public static final int COMA = 9;
  public static final int NUMBER = 26;
  public static final int EOF = 0;
  public static final int DIVIDE = 6;
  public static final int MOVE_DOWN = 21;
  public static final int ASSIGFOR = 19;
  public static final int MINUS = 4;
  public static final int SET_CURSOR = 20;
  public static final int PRINT = 12;
  public static final int error = 1;
  public static final int ASSIGN = 11;
  public static final int FOR = 13;
  public static final int TO = 14;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMI",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVIDE",
  "LPAREN",
  "RPAREN",
  "COMA",
  "COLON",
  "ASSIGN",
  "PRINT",
  "FOR",
  "TO",
  "DO",
  "END",
  "LBRACK",
  "RBRACK",
  "ASSIGFOR",
  "SET_CURSOR",
  "MOVE_DOWN",
  "MOVE_UP",
  "MOVE_LEFT",
  "MOVE_RIGHT",
  "SET_COLOR",
  "NUMBER",
  "ID"
  };
}

